package com.model.dao;

import com.model.base.BaseQcmQuestionDAO;

/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is the object class that relates to the qcm_question table.
 * Any customizations belong here.
 */
public class QcmQuestionDAO extends BaseQcmQuestionDAO {
}