package model.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the etudiant table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="etudiant"
 */
public abstract class BaseEtudiant  implements Serializable {

	public static String PROP_NOM = "Nom";
	public static String PROP_ID_UTILISATEUR = "IdUtilisateur";
	public static String PROP_PRENOM = "Prenom";
	public static String PROP_ID_ETUDIANT = "IdEtudiant";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _idEtudiant;

	// fields
	private java.lang.String _prenom;
	private java.lang.String _nom;

	// many to one
	private model.Utilisateur _idUtilisateur;

	// collections
	private java.util.Set _etudiantQcmSet;
	private java.util.Set _etudiantClasseSet;


	// constructors
	public BaseEtudiant () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseEtudiant (java.lang.Integer _idEtudiant) {
		this.setIdEtudiant(_idEtudiant);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseEtudiant (
		java.lang.Integer _idEtudiant,
		model.Utilisateur _idUtilisateur,
		java.lang.String _prenom,
		java.lang.String _nom) {

		this.setIdEtudiant(_idEtudiant);
		this.setIdUtilisateur(_idUtilisateur);
		this.setPrenom(_prenom);
		this.setNom(_nom);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="increment"
     *  column="id_etudiant"
     */
	public java.lang.Integer getIdEtudiant () {
		return _idEtudiant;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _idEtudiant the new ID
	 */
	public void setIdEtudiant (java.lang.Integer _idEtudiant) {
		this._idEtudiant = _idEtudiant;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: prenom
	 */
	public java.lang.String getPrenom () {
		return _prenom;
	}

	/**
	 * Set the value related to the column: prenom
	 * @param _prenom the prenom value
	 */
	public void setPrenom (java.lang.String _prenom) {
		this._prenom = _prenom;
	}


	/**
	 * Return the value associated with the column: nom
	 */
	public java.lang.String getNom () {
		return _nom;
	}

	/**
	 * Set the value related to the column: nom
	 * @param _nom the nom value
	 */
	public void setNom (java.lang.String _nom) {
		this._nom = _nom;
	}


	/**
     * @hibernate.property
     *  column=id_utilisateur
	 * not-null=true
	 */
	public model.Utilisateur getIdUtilisateur () {
		return this._idUtilisateur;
	}

	/**
	 * Set the value related to the column: id_utilisateur
	 * @param _idUtilisateur the id_utilisateur value
	 */
	public void setIdUtilisateur (model.Utilisateur _idUtilisateur) {
		this._idUtilisateur = _idUtilisateur;
	}


	/**
	 * Return the value associated with the column: EtudiantQcmSet
	 */
	public java.util.Set getEtudiantQcmSet () {
		return this._etudiantQcmSet;
	}

	/**
	 * Set the value related to the column: EtudiantQcmSet
	 * @param _etudiantQcmSet the EtudiantQcmSet value
	 */
	public void setEtudiantQcmSet (java.util.Set _etudiantQcmSet) {
		this._etudiantQcmSet = _etudiantQcmSet;
	}
	
	public void addToEtudiantQcmSet (Object obj) {
		if (null == this._etudiantQcmSet) this._etudiantQcmSet = new java.util.HashSet();
		this._etudiantQcmSet.add(obj);
	}



	/**
	 * Return the value associated with the column: EtudiantClasseSet
	 */
	public java.util.Set getEtudiantClasseSet () {
		return this._etudiantClasseSet;
	}

	/**
	 * Set the value related to the column: EtudiantClasseSet
	 * @param _etudiantClasseSet the EtudiantClasseSet value
	 */
	public void setEtudiantClasseSet (java.util.Set _etudiantClasseSet) {
		this._etudiantClasseSet = _etudiantClasseSet;
	}
	
	public void addToEtudiantClasseSet (Object obj) {
		if (null == this._etudiantClasseSet) this._etudiantClasseSet = new java.util.HashSet();
		this._etudiantClasseSet.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof model.base.BaseEtudiant)) return false;
		else {
			model.base.BaseEtudiant mObj = (model.base.BaseEtudiant) obj;
			if (null == this.getIdEtudiant() || null == mObj.getIdEtudiant()) return false;
			else return (this.getIdEtudiant().equals(mObj.getIdEtudiant()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getIdEtudiant()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getIdEtudiant().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}