package com.model.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the qcm table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="qcm"
 */
public abstract class BaseQcm  implements Serializable {

	public static String PROP_DATE_FIN = "DateFin";
	public static String PROP_DATE_DEBUT = "DateDebut";
	public static String PROP_ID_PROFESSEUR = "IdProfesseur";
	public static String PROP_NOM = "Nom";
	public static String PROP_ID_QCM = "IdQcm";
	public static String PROP_DATE_CREATION = "DateCreation";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _idQcm;

	// fields
	private java.util.Date _dateCreation;
	private java.util.Date _dateDebut;
	private java.util.Date _dateFin;
	private java.lang.String _nom;

	// many to one
	private com.model.Professeur _idProfesseur;

	// collections
	private java.util.Set _qcmQuestionSet;
	private java.util.Set _etudiantQcmSet;


	// constructors
	public BaseQcm () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseQcm (java.lang.Integer _idQcm) {
		this.setIdQcm(_idQcm);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseQcm (
		java.lang.Integer _idQcm,
		com.model.Professeur _idProfesseur,
		java.util.Date _dateCreation,
		java.util.Date _dateDebut,
		java.util.Date _dateFin,
		java.lang.String _nom) {

		this.setIdQcm(_idQcm);
		this.setIdProfesseur(_idProfesseur);
		this.setDateCreation(_dateCreation);
		this.setDateDebut(_dateDebut);
		this.setDateFin(_dateFin);
		this.setNom(_nom);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="increment"
     *  column="id_qcm"
     */
	public java.lang.Integer getIdQcm () {
		return _idQcm;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _idQcm the new ID
	 */
	public void setIdQcm (java.lang.Integer _idQcm) {
		this._idQcm = _idQcm;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: date_creation
	 */
	public java.util.Date getDateCreation () {
		return _dateCreation;
	}

	/**
	 * Set the value related to the column: date_creation
	 * @param _dateCreation the date_creation value
	 */
	public void setDateCreation (java.util.Date _dateCreation) {
		this._dateCreation = _dateCreation;
	}


	/**
	 * Return the value associated with the column: date_debut
	 */
	public java.util.Date getDateDebut () {
		return _dateDebut;
	}

	/**
	 * Set the value related to the column: date_debut
	 * @param _dateDebut the date_debut value
	 */
	public void setDateDebut (java.util.Date _dateDebut) {
		this._dateDebut = _dateDebut;
	}


	/**
	 * Return the value associated with the column: date_fin
	 */
	public java.util.Date getDateFin () {
		return _dateFin;
	}

	/**
	 * Set the value related to the column: date_fin
	 * @param _dateFin the date_fin value
	 */
	public void setDateFin (java.util.Date _dateFin) {
		this._dateFin = _dateFin;
	}


	/**
	 * Return the value associated with the column: nom
	 */
	public java.lang.String getNom () {
		return _nom;
	}

	/**
	 * Set the value related to the column: nom
	 * @param _nom the nom value
	 */
	public void setNom (java.lang.String _nom) {
		this._nom = _nom;
	}


	/**
     * @hibernate.property
     *  column=id_professeur
	 * not-null=true
	 */
	public com.model.Professeur getIdProfesseur () {
		return this._idProfesseur;
	}

	/**
	 * Set the value related to the column: id_professeur
	 * @param _idProfesseur the id_professeur value
	 */
	public void setIdProfesseur (com.model.Professeur _idProfesseur) {
		this._idProfesseur = _idProfesseur;
	}


	/**
	 * Return the value associated with the column: QcmQuestionSet
	 */
	public java.util.Set getQcmQuestionSet () {
		return this._qcmQuestionSet;
	}

	/**
	 * Set the value related to the column: QcmQuestionSet
	 * @param _qcmQuestionSet the QcmQuestionSet value
	 */
	public void setQcmQuestionSet (java.util.Set _qcmQuestionSet) {
		this._qcmQuestionSet = _qcmQuestionSet;
	}
	
	public void addToQcmQuestionSet (Object obj) {
		if (null == this._qcmQuestionSet) this._qcmQuestionSet = new java.util.HashSet();
		this._qcmQuestionSet.add(obj);
	}



	/**
	 * Return the value associated with the column: EtudiantQcmSet
	 */
	public java.util.Set getEtudiantQcmSet () {
		return this._etudiantQcmSet;
	}

	/**
	 * Set the value related to the column: EtudiantQcmSet
	 * @param _etudiantQcmSet the EtudiantQcmSet value
	 */
	public void setEtudiantQcmSet (java.util.Set _etudiantQcmSet) {
		this._etudiantQcmSet = _etudiantQcmSet;
	}
	
	public void addToEtudiantQcmSet (Object obj) {
		if (null == this._etudiantQcmSet) this._etudiantQcmSet = new java.util.HashSet();
		this._etudiantQcmSet.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof com.model.base.BaseQcm)) return false;
		else {
			com.model.base.BaseQcm mObj = (com.model.base.BaseQcm) obj;
			if (null == this.getIdQcm() || null == mObj.getIdQcm()) return false;
			else return (this.getIdQcm().equals(mObj.getIdQcm()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getIdQcm()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getIdQcm().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}