package com.model.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the qcm_question table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="qcm_question"
 */
public abstract class BaseQcmQuestion  implements Serializable {

	public static String PROP_ID_QCMQUESTION = "IdQcmquestion";
	public static String PROP_ID_QCM = "IdQcm";
	public static String PROP_ID_QUESTION = "IdQuestion";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _idQcmquestion;

	// many to one
	private com.model.Qcm _idQcm;
	private com.model.Question _idQuestion;


	// constructors
	public BaseQcmQuestion () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseQcmQuestion (java.lang.Integer _idQcmquestion) {
		this.setIdQcmquestion(_idQcmquestion);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseQcmQuestion (
		java.lang.Integer _idQcmquestion,
		com.model.Qcm _idQcm,
		com.model.Question _idQuestion) {

		this.setIdQcmquestion(_idQcmquestion);
		this.setIdQcm(_idQcm);
		this.setIdQuestion(_idQuestion);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="increment"
     *  column="id_qcmquestion"
     */
	public java.lang.Integer getIdQcmquestion () {
		return _idQcmquestion;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _idQcmquestion the new ID
	 */
	public void setIdQcmquestion (java.lang.Integer _idQcmquestion) {
		this._idQcmquestion = _idQcmquestion;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
     * @hibernate.property
     *  column=id_qcm
	 * not-null=true
	 */
	public com.model.Qcm getIdQcm () {
		return this._idQcm;
	}

	/**
	 * Set the value related to the column: id_qcm
	 * @param _idQcm the id_qcm value
	 */
	public void setIdQcm (com.model.Qcm _idQcm) {
		this._idQcm = _idQcm;
	}


	/**
     * @hibernate.property
     *  column=id_question
	 * not-null=true
	 */
	public com.model.Question getIdQuestion () {
		return this._idQuestion;
	}

	/**
	 * Set the value related to the column: id_question
	 * @param _idQuestion the id_question value
	 */
	public void setIdQuestion (com.model.Question _idQuestion) {
		this._idQuestion = _idQuestion;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof com.model.base.BaseQcmQuestion)) return false;
		else {
			com.model.base.BaseQcmQuestion mObj = (com.model.base.BaseQcmQuestion) obj;
			if (null == this.getIdQcmquestion() || null == mObj.getIdQcmquestion()) return false;
			else return (this.getIdQcmquestion().equals(mObj.getIdQcmquestion()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getIdQcmquestion()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getIdQcmquestion().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}