package com.model.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the etudiant_qcm table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="etudiant_qcm"
 */
public abstract class BaseEtudiantQcm  implements Serializable {

	public static String PROP_ID_ETUDIANTQCM = "IdEtudiantqcm";
	public static String PROP_ID_QCM = "IdQcm";
	public static String PROP_NOTE = "Note";
	public static String PROP_ID_ETUDIANT = "IdEtudiant";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _idEtudiantqcm;

	// fields
	private java.lang.Float _note;

	// many to one
	private com.model.Qcm _idQcm;
	private com.model.Etudiant _idEtudiant;


	// constructors
	public BaseEtudiantQcm () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseEtudiantQcm (java.lang.Integer _idEtudiantqcm) {
		this.setIdEtudiantqcm(_idEtudiantqcm);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseEtudiantQcm (
		java.lang.Integer _idEtudiantqcm,
		com.model.Qcm _idQcm,
		com.model.Etudiant _idEtudiant,
		java.lang.Float _note) {

		this.setIdEtudiantqcm(_idEtudiantqcm);
		this.setIdQcm(_idQcm);
		this.setIdEtudiant(_idEtudiant);
		this.setNote(_note);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="increment"
     *  column="id_etudiantqcm"
     */
	public java.lang.Integer getIdEtudiantqcm () {
		return _idEtudiantqcm;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _idEtudiantqcm the new ID
	 */
	public void setIdEtudiantqcm (java.lang.Integer _idEtudiantqcm) {
		this._idEtudiantqcm = _idEtudiantqcm;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: note
	 */
	public java.lang.Float getNote () {
		return _note;
	}

	/**
	 * Set the value related to the column: note
	 * @param _note the note value
	 */
	public void setNote (java.lang.Float _note) {
		this._note = _note;
	}


	/**
     * @hibernate.property
     *  column=id_qcm
	 * not-null=true
	 */
	public com.model.Qcm getIdQcm () {
		return this._idQcm;
	}

	/**
	 * Set the value related to the column: id_qcm
	 * @param _idQcm the id_qcm value
	 */
	public void setIdQcm (com.model.Qcm _idQcm) {
		this._idQcm = _idQcm;
	}


	/**
     * @hibernate.property
     *  column=id_etudiant
	 * not-null=true
	 */
	public com.model.Etudiant getIdEtudiant () {
		return this._idEtudiant;
	}

	/**
	 * Set the value related to the column: id_etudiant
	 * @param _idEtudiant the id_etudiant value
	 */
	public void setIdEtudiant (com.model.Etudiant _idEtudiant) {
		this._idEtudiant = _idEtudiant;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof com.model.base.BaseEtudiantQcm)) return false;
		else {
			com.model.base.BaseEtudiantQcm mObj = (com.model.base.BaseEtudiantQcm) obj;
			if (null == this.getIdEtudiantqcm() || null == mObj.getIdEtudiantqcm()) return false;
			else return (this.getIdEtudiantqcm().equals(mObj.getIdEtudiantqcm()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getIdEtudiantqcm()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getIdEtudiantqcm().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}