package com.model.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the administrateur table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="administrateur"
 */
public abstract class BaseAdministrateur  implements Serializable {

	public static String PROP_NOM = "Nom";
	public static String PROP_ID_UTILISATEUR = "IdUtilisateur";
	public static String PROP_ID_ADMINISTRATEUR = "IdAdministrateur";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _idAdministrateur;

	// fields
	private java.lang.String _nom;

	// many to one
	private com.model.Utilisateur _idUtilisateur;


	// constructors
	public BaseAdministrateur () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseAdministrateur (java.lang.Integer _idAdministrateur) {
		this.setIdAdministrateur(_idAdministrateur);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseAdministrateur (
		java.lang.Integer _idAdministrateur,
		com.model.Utilisateur _idUtilisateur,
		java.lang.String _nom) {

		this.setIdAdministrateur(_idAdministrateur);
		this.setIdUtilisateur(_idUtilisateur);
		this.setNom(_nom);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="increment"
     *  column="id_administrateur"
     */
	public java.lang.Integer getIdAdministrateur () {
		return _idAdministrateur;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _idAdministrateur the new ID
	 */
	public void setIdAdministrateur (java.lang.Integer _idAdministrateur) {
		this._idAdministrateur = _idAdministrateur;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: nom
	 */
	public java.lang.String getNom () {
		return _nom;
	}

	/**
	 * Set the value related to the column: nom
	 * @param _nom the nom value
	 */
	public void setNom (java.lang.String _nom) {
		this._nom = _nom;
	}


	/**
     * @hibernate.property
     *  column=id_utilisateur
	 * not-null=true
	 */
	public com.model.Utilisateur getIdUtilisateur () {
		return this._idUtilisateur;
	}

	/**
	 * Set the value related to the column: id_utilisateur
	 * @param _idUtilisateur the id_utilisateur value
	 */
	public void setIdUtilisateur (com.model.Utilisateur _idUtilisateur) {
		this._idUtilisateur = _idUtilisateur;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof com.model.base.BaseAdministrateur)) return false;
		else {
			com.model.base.BaseAdministrateur mObj = (com.model.base.BaseAdministrateur) obj;
			if (null == this.getIdAdministrateur() || null == mObj.getIdAdministrateur()) return false;
			else return (this.getIdAdministrateur().equals(mObj.getIdAdministrateur()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getIdAdministrateur()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getIdAdministrateur().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}