package com.model.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the matiere table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="matiere"
 */
public abstract class BaseMatiere  implements Serializable {

	public static String PROP_ID_MATIERE = "IdMatiere";
	public static String PROP_NOM = "Nom";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _idMatiere;

	// fields
	private java.lang.String _nom;

	// collections
	private java.util.Set _professeurMatiereSet;


	// constructors
	public BaseMatiere () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseMatiere (java.lang.Integer _idMatiere) {
		this.setIdMatiere(_idMatiere);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseMatiere (
		java.lang.Integer _idMatiere,
		java.lang.String _nom) {

		this.setIdMatiere(_idMatiere);
		this.setNom(_nom);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="increment"
     *  column="id_matiere"
     */
	public java.lang.Integer getIdMatiere () {
		return _idMatiere;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _idMatiere the new ID
	 */
	public void setIdMatiere (java.lang.Integer _idMatiere) {
		this._idMatiere = _idMatiere;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: nom
	 */
	public java.lang.String getNom () {
		return _nom;
	}

	/**
	 * Set the value related to the column: nom
	 * @param _nom the nom value
	 */
	public void setNom (java.lang.String _nom) {
		this._nom = _nom;
	}


	/**
	 * Return the value associated with the column: ProfesseurMatiereSet
	 */
	public java.util.Set getProfesseurMatiereSet () {
		return this._professeurMatiereSet;
	}

	/**
	 * Set the value related to the column: ProfesseurMatiereSet
	 * @param _professeurMatiereSet the ProfesseurMatiereSet value
	 */
	public void setProfesseurMatiereSet (java.util.Set _professeurMatiereSet) {
		this._professeurMatiereSet = _professeurMatiereSet;
	}
	
	public void addToProfesseurMatiereSet (Object obj) {
		if (null == this._professeurMatiereSet) this._professeurMatiereSet = new java.util.HashSet();
		this._professeurMatiereSet.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof com.model.base.BaseMatiere)) return false;
		else {
			com.model.base.BaseMatiere mObj = (com.model.base.BaseMatiere) obj;
			if (null == this.getIdMatiere() || null == mObj.getIdMatiere()) return false;
			else return (this.getIdMatiere().equals(mObj.getIdMatiere()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getIdMatiere()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getIdMatiere().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}