package com.model.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the professeur table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="professeur"
 */
public abstract class BaseProfesseur  implements Serializable {

	public static String PROP_ID_PROFESSEUR = "IdProfesseur";
	public static String PROP_NOM = "Nom";
	public static String PROP_ID_UTILISATEUR = "IdUtilisateur";
	public static String PROP_PRENOM = "Prenom";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _idProfesseur;

	// fields
	private java.lang.String _prenom;
	private java.lang.String _nom;

	// many to one
	private com.model.Utilisateur _idUtilisateur;

	// collections
	private java.util.Set _questionSet;
	private java.util.Set _professeurMatiereSet;
	private java.util.Set _qcmSet;


	// constructors
	public BaseProfesseur () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseProfesseur (java.lang.Integer _idProfesseur) {
		this.setIdProfesseur(_idProfesseur);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseProfesseur (
		java.lang.Integer _idProfesseur,
		com.model.Utilisateur _idUtilisateur,
		java.lang.String _prenom,
		java.lang.String _nom) {

		this.setIdProfesseur(_idProfesseur);
		this.setIdUtilisateur(_idUtilisateur);
		this.setPrenom(_prenom);
		this.setNom(_nom);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="increment"
     *  column="id_professeur"
     */
	public java.lang.Integer getIdProfesseur () {
		return _idProfesseur;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _idProfesseur the new ID
	 */
	public void setIdProfesseur (java.lang.Integer _idProfesseur) {
		this._idProfesseur = _idProfesseur;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: prenom
	 */
	public java.lang.String getPrenom () {
		return _prenom;
	}

	/**
	 * Set the value related to the column: prenom
	 * @param _prenom the prenom value
	 */
	public void setPrenom (java.lang.String _prenom) {
		this._prenom = _prenom;
	}


	/**
	 * Return the value associated with the column: nom
	 */
	public java.lang.String getNom () {
		return _nom;
	}

	/**
	 * Set the value related to the column: nom
	 * @param _nom the nom value
	 */
	public void setNom (java.lang.String _nom) {
		this._nom = _nom;
	}


	/**
     * @hibernate.property
     *  column=id_utilisateur
	 * not-null=true
	 */
	public com.model.Utilisateur getIdUtilisateur () {
		return this._idUtilisateur;
	}

	/**
	 * Set the value related to the column: id_utilisateur
	 * @param _idUtilisateur the id_utilisateur value
	 */
	public void setIdUtilisateur (com.model.Utilisateur _idUtilisateur) {
		this._idUtilisateur = _idUtilisateur;
	}


	/**
	 * Return the value associated with the column: QuestionSet
	 */
	public java.util.Set getQuestionSet () {
		return this._questionSet;
	}

	/**
	 * Set the value related to the column: QuestionSet
	 * @param _questionSet the QuestionSet value
	 */
	public void setQuestionSet (java.util.Set _questionSet) {
		this._questionSet = _questionSet;
	}
	
	public void addToQuestionSet (Object obj) {
		if (null == this._questionSet) this._questionSet = new java.util.HashSet();
		this._questionSet.add(obj);
	}



	/**
	 * Return the value associated with the column: ProfesseurMatiereSet
	 */
	public java.util.Set getProfesseurMatiereSet () {
		return this._professeurMatiereSet;
	}

	/**
	 * Set the value related to the column: ProfesseurMatiereSet
	 * @param _professeurMatiereSet the ProfesseurMatiereSet value
	 */
	public void setProfesseurMatiereSet (java.util.Set _professeurMatiereSet) {
		this._professeurMatiereSet = _professeurMatiereSet;
	}
	
	public void addToProfesseurMatiereSet (Object obj) {
		if (null == this._professeurMatiereSet) this._professeurMatiereSet = new java.util.HashSet();
		this._professeurMatiereSet.add(obj);
	}



	/**
	 * Return the value associated with the column: QcmSet
	 */
	public java.util.Set getQcmSet () {
		return this._qcmSet;
	}

	/**
	 * Set the value related to the column: QcmSet
	 * @param _qcmSet the QcmSet value
	 */
	public void setQcmSet (java.util.Set _qcmSet) {
		this._qcmSet = _qcmSet;
	}
	
	public void addToQcmSet (Object obj) {
		if (null == this._qcmSet) this._qcmSet = new java.util.HashSet();
		this._qcmSet.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof com.model.base.BaseProfesseur)) return false;
		else {
			com.model.base.BaseProfesseur mObj = (com.model.base.BaseProfesseur) obj;
			if (null == this.getIdProfesseur() || null == mObj.getIdProfesseur()) return false;
			else return (this.getIdProfesseur().equals(mObj.getIdProfesseur()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getIdProfesseur()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getIdProfesseur().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}