package com.model.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the etudiant_classe table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="etudiant_classe"
 */
public abstract class BaseEtudiantClasse  implements Serializable {

	public static String PROP_ID_ETUDIANTCLASSE = "IdEtudiantclasse";
	public static String PROP_ID_CLASSE = "IdClasse";
	public static String PROP_ID_ETUDIANT = "IdEtudiant";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _idEtudiantclasse;

	// many to one
	private com.model.Etudiant _idEtudiant;
	private com.model.Classe _idClasse;


	// constructors
	public BaseEtudiantClasse () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseEtudiantClasse (java.lang.Integer _idEtudiantclasse) {
		this.setIdEtudiantclasse(_idEtudiantclasse);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseEtudiantClasse (
		java.lang.Integer _idEtudiantclasse,
		com.model.Etudiant _idEtudiant,
		com.model.Classe _idClasse) {

		this.setIdEtudiantclasse(_idEtudiantclasse);
		this.setIdEtudiant(_idEtudiant);
		this.setIdClasse(_idClasse);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="increment"
     *  column="id_etudiantclasse"
     */
	public java.lang.Integer getIdEtudiantclasse () {
		return _idEtudiantclasse;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _idEtudiantclasse the new ID
	 */
	public void setIdEtudiantclasse (java.lang.Integer _idEtudiantclasse) {
		this._idEtudiantclasse = _idEtudiantclasse;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
     * @hibernate.property
     *  column=id_etudiant
	 * not-null=true
	 */
	public com.model.Etudiant getIdEtudiant () {
		return this._idEtudiant;
	}

	/**
	 * Set the value related to the column: id_etudiant
	 * @param _idEtudiant the id_etudiant value
	 */
	public void setIdEtudiant (com.model.Etudiant _idEtudiant) {
		this._idEtudiant = _idEtudiant;
	}


	/**
     * @hibernate.property
     *  column=id_classe
	 * not-null=true
	 */
	public com.model.Classe getIdClasse () {
		return this._idClasse;
	}

	/**
	 * Set the value related to the column: id_classe
	 * @param _idClasse the id_classe value
	 */
	public void setIdClasse (com.model.Classe _idClasse) {
		this._idClasse = _idClasse;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof com.model.base.BaseEtudiantClasse)) return false;
		else {
			com.model.base.BaseEtudiantClasse mObj = (com.model.base.BaseEtudiantClasse) obj;
			if (null == this.getIdEtudiantclasse() || null == mObj.getIdEtudiantclasse()) return false;
			else return (this.getIdEtudiantclasse().equals(mObj.getIdEtudiantclasse()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getIdEtudiantclasse()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getIdEtudiantclasse().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}