package com.model.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the classe table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="classe"
 */
public abstract class BaseClasse  implements Serializable {

	public static String PROP_NOM = "Nom";
	public static String PROP_ID_CLASSE = "IdClasse";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _idClasse;

	// fields
	private java.lang.String _nom;

	// collections
	private java.util.Set _etudiantClasseSet;


	// constructors
	public BaseClasse () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseClasse (java.lang.Integer _idClasse) {
		this.setIdClasse(_idClasse);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseClasse (
		java.lang.Integer _idClasse,
		java.lang.String _nom) {

		this.setIdClasse(_idClasse);
		this.setNom(_nom);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="increment"
     *  column="id_classe"
     */
	public java.lang.Integer getIdClasse () {
		return _idClasse;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _idClasse the new ID
	 */
	public void setIdClasse (java.lang.Integer _idClasse) {
		this._idClasse = _idClasse;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: nom
	 */
	public java.lang.String getNom () {
		return _nom;
	}

	/**
	 * Set the value related to the column: nom
	 * @param _nom the nom value
	 */
	public void setNom (java.lang.String _nom) {
		this._nom = _nom;
	}


	/**
	 * Return the value associated with the column: EtudiantClasseSet
	 */
	public java.util.Set getEtudiantClasseSet () {
		return this._etudiantClasseSet;
	}

	/**
	 * Set the value related to the column: EtudiantClasseSet
	 * @param _etudiantClasseSet the EtudiantClasseSet value
	 */
	public void setEtudiantClasseSet (java.util.Set _etudiantClasseSet) {
		this._etudiantClasseSet = _etudiantClasseSet;
	}
	
	public void addToEtudiantClasseSet (Object obj) {
		if (null == this._etudiantClasseSet) this._etudiantClasseSet = new java.util.HashSet();
		this._etudiantClasseSet.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof com.model.base.BaseClasse)) return false;
		else {
			com.model.base.BaseClasse mObj = (com.model.base.BaseClasse) obj;
			if (null == this.getIdClasse() || null == mObj.getIdClasse()) return false;
			else return (this.getIdClasse().equals(mObj.getIdClasse()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getIdClasse()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getIdClasse().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}